/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicYoutubeRouteImport } from './routes/api/public/youtube'
import { Route as ApiPublicBlogRouteImport } from './routes/api/public/blog'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicYoutubeRoute = ApiPublicYoutubeRouteImport.update({
  id: '/api/public/youtube',
  path: '/api/public/youtube',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBlogRoute = ApiPublicBlogRouteImport.update({
  id: '/api/public/blog',
  path: '/api/public/blog',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/api/public/youtube': typeof ApiPublicYoutubeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/api/public/youtube': typeof ApiPublicYoutubeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/blog': typeof ApiPublicBlogRoute
  '/api/public/youtube': typeof ApiPublicYoutubeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/blog' | '/api/public/youtube'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/blog' | '/api/public/youtube'
  id: '__root__' | '/' | '/api/public/blog' | '/api/public/youtube'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicBlogRoute: typeof ApiPublicBlogRoute
  ApiPublicYoutubeRoute: typeof ApiPublicYoutubeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/youtube': {
      id: '/api/public/youtube'
      path: '/api/public/youtube'
      fullPath: '/api/public/youtube'
      preLoaderRoute: typeof ApiPublicYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/blog': {
      id: '/api/public/blog'
      path: '/api/public/blog'
      fullPath: '/api/public/blog'
      preLoaderRoute: typeof ApiPublicBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicBlogRoute: ApiPublicBlogRoute,
  ApiPublicYoutubeRoute: ApiPublicYoutubeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
